on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  dotnet-format:
    runs-on: ubuntu-latest
    steps:   
      - name: Super-Linter          
        uses: super-linter/super-linter@v5.7.1

