name: CSSuperLinter
on:
  push:
    branches:
    - main
    paths:
        - "**/*.cs"
        - ".github/workflows/main.yml"
  workflow_dispatch:

jobs:
  dotnet-format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
    
      - name: Glob Match
        id: glob
        uses: zyactions/glob@v2
        with:
          pattern: |
            Assets/Scripts/*.cs
          return-pipe: true
    
      - name: .NET Lint
        uses: zyactions/dotnet-lint@v1
        
   #   - name: Super-Linter          
   #     uses: super-linter/super-linter@v5.7.1
   #     with:
  #       path: ${{ github.workspace }}
   #       name: ${{ env.VERSION_MAJOR }}.${{ env.VERSION_MINOR }}

